package com.lolpicker.rules;

import com.lolpicker.model.ChampionPick;
import com.lolpicker.model.ChampionSelect;
import com.lolpicker.model.Champion;
import com.lolpicker.model.Position;

rule "champions by tier, top"
	when
		$cs: ChampionSelect(myPosition == Position.top)
	then
		$cs.getChampsForPosition().add(Champion.Darius);
		$cs.getChampsForPosition().add(Champion.Urgot);
		$cs.getChampsForPosition().add(Champion.Garen);
		$cs.getChampsForPosition().add(Champion.Sett);
		$cs.getChampsForPosition().add(Champion.Mordekaiser);
		$cs.getChampsForPosition().add(Champion.Maokai);
		$cs.getChampsForPosition().add(Champion.Wukong);
		$cs.getChampsForPosition().add(Champion.Kled);
		$cs.getChampsForPosition().add(Champion.Fiora);
		$cs.getChampsForPosition().add(Champion.Jax);
		$cs.getChampsForPosition().add(Champion.Renekton);
		$cs.getChampsForPosition().add(Champion.Illaoi);
		$cs.getChampsForPosition().add(Champion.Tryndamere);
		$cs.getChampsForPosition().add(Champion.Ornn);
		$cs.getChampsForPosition().add(Champion.Sion);
		$cs.getChampsForPosition().add(Champion.Gangplank);
		$cs.getChampsForPosition().add(Champion.Singed);
		$cs.getChampsForPosition().add(Champion.Teemo);
		$cs.getChampsForPosition().add(Champion.Shen);
		$cs.getChampsForPosition().add(Champion.Nasus);
		$cs.getChampsForPosition().add(Champion.Irelia);
		$cs.getChampsForPosition().add(Champion.Kayle);
		$cs.getChampsForPosition().add(Champion.Camille);
		$cs.getChampsForPosition().add(Champion.Vladimir);
		$cs.getChampsForPosition().add(Champion.Aatrox);
		$cs.getChampsForPosition().add(Champion.Gnar);
		$cs.getChampsForPosition().add(Champion.Malphite);
		$cs.getChampsForPosition().add(Champion.Riven);
		$cs.getChampsForPosition().add(Champion.Poppy);
end

rule "champions by tier, jungle"
	when
		$cs: ChampionSelect(myPosition == Position.jungle)
	then
		$cs.getChampsForPosition().add(Champion.Ekko);
		$cs.getChampsForPosition().add(Champion.Kayn);
		$cs.getChampsForPosition().add(Champion.LeeSin);
		$cs.getChampsForPosition().add(Champion.Warwick);
		$cs.getChampsForPosition().add(Champion.Zac);
		$cs.getChampsForPosition().add(Champion.MasterYi);
		$cs.getChampsForPosition().add(Champion.Karthus);
		$cs.getChampsForPosition().add(Champion.Graves);
		$cs.getChampsForPosition().add(Champion.Shaco);
		$cs.getChampsForPosition().add(Champion.Shyvana);
		$cs.getChampsForPosition().add(Champion.Olaf);
		$cs.getChampsForPosition().add(Champion.Wukong);
		$cs.getChampsForPosition().add(Champion.KhaZix);
		$cs.getChampsForPosition().add(Champion.NunuAndWillump);
		$cs.getChampsForPosition().add(Champion.Trundle);
		$cs.getChampsForPosition().add(Champion.Rengar);
		$cs.getChampsForPosition().add(Champion.Hecarim);
		$cs.getChampsForPosition().add(Champion.Elise);
		$cs.getChampsForPosition().add(Champion.Nocturne);
		$cs.getChampsForPosition().add(Champion.Sejuani);
		$cs.getChampsForPosition().add(Champion.JarvanIV);
		$cs.getChampsForPosition().add(Champion.Volibear);
		$cs.getChampsForPosition().add(Champion.RekSai);
		$cs.getChampsForPosition().add(Champion.Rammus);
		$cs.getChampsForPosition().add(Champion.Amumu);
		$cs.getChampsForPosition().add(Champion.Nidalee);
		$cs.getChampsForPosition().add(Champion.Udyr);
		$cs.getChampsForPosition().add(Champion.Evelynn);
		$cs.getChampsForPosition().add(Champion.Kindred);
		$cs.getChampsForPosition().add(Champion.XinZhao);
		$cs.getChampsForPosition().add(Champion.Vi);
		$cs.getChampsForPosition().add(Champion.Gragas);
end

rule "champions by tier, mid"
	when
		$cs: ChampionSelect(myPosition == Position.mid)
	then
		$cs.getChampsForPosition().add(Champion.Zed);
		$cs.getChampsForPosition().add(Champion.Kassadin);
		$cs.getChampsForPosition().add(Champion.Diana);
		$cs.getChampsForPosition().add(Champion.Yasuo);
		$cs.getChampsForPosition().add(Champion.Katarina);
		$cs.getChampsForPosition().add(Champion.Vladimir);
		$cs.getChampsForPosition().add(Champion.Ziggs);
		$cs.getChampsForPosition().add(Champion.Fizz);
		$cs.getChampsForPosition().add(Champion.Talon);
		$cs.getChampsForPosition().add(Champion.Cassiopeia);
		$cs.getChampsForPosition().add(Champion.Viktor);
		$cs.getChampsForPosition().add(Champion.Ahri);
		$cs.getChampsForPosition().add(Champion.Syndra);
		$cs.getChampsForPosition().add(Champion.LeBlanc);
		$cs.getChampsForPosition().add(Champion.Veigar);
		$cs.getChampsForPosition().add(Champion.Malzahar);
		$cs.getChampsForPosition().add(Champion.Orianna);
		$cs.getChampsForPosition().add(Champion.Sylas);
		$cs.getChampsForPosition().add(Champion.Zoe);
		$cs.getChampsForPosition().add(Champion.Anivia);
		$cs.getChampsForPosition().add(Champion.Annie);
		$cs.getChampsForPosition().add(Champion.Zilean);
		$cs.getChampsForPosition().add(Champion.AurelionSol);
		$cs.getChampsForPosition().add(Champion.Neeko);
		$cs.getChampsForPosition().add(Champion.Qiyana);
		$cs.getChampsForPosition().add(Champion.Pantheon);
		$cs.getChampsForPosition().add(Champion.TwistedFate);
		$cs.getChampsForPosition().add(Champion.Lissandra);
		$cs.getChampsForPosition().add(Champion.Ryze);
		$cs.getChampsForPosition().add(Champion.Azir);
		$cs.getChampsForPosition().add(Champion.Akali);
end

rule "champions by tier, bot"
	when
		$cs: ChampionSelect(myPosition == Position.bot)
	then
		$cs.getChampsForPosition().add(Champion.MissFortune);
		$cs.getChampsForPosition().add(Champion.Jhin);
		$cs.getChampsForPosition().add(Champion.Ezreal);
		$cs.getChampsForPosition().add(Champion.Caitlyn);
		$cs.getChampsForPosition().add(Champion.Vayne);
		$cs.getChampsForPosition().add(Champion.Ashe);
		$cs.getChampsForPosition().add(Champion.Varus);
		$cs.getChampsForPosition().add(Champion.Jinx);
		$cs.getChampsForPosition().add(Champion.Syndra);
		$cs.getChampsForPosition().add(Champion.Sivir);
		$cs.getChampsForPosition().add(Champion.KaiSa);
		$cs.getChampsForPosition().add(Champion.Lucian);
		$cs.getChampsForPosition().add(Champion.Draven);
		$cs.getChampsForPosition().add(Champion.Tristana);
		$cs.getChampsForPosition().add(Champion.Twitch);
		$cs.getChampsForPosition().add(Champion.Aphelios);
		$cs.getChampsForPosition().add(Champion.Kalista);
		$cs.getChampsForPosition().add(Champion.Heimerdinger);
		$cs.getChampsForPosition().add(Champion.Xayah);
end

rule "champions by tier, support"
	when
		$cs: ChampionSelect(myPosition == Position.support)
	then
		$cs.getChampsForPosition().add(Champion.Senna);
		$cs.getChampsForPosition().add(Champion.Blitzcrank);
		$cs.getChampsForPosition().add(Champion.Nami);
		$cs.getChampsForPosition().add(Champion.Pyke);
		$cs.getChampsForPosition().add(Champion.Thresh);
		$cs.getChampsForPosition().add(Champion.Morgana);
		$cs.getChampsForPosition().add(Champion.Nautilus);
		$cs.getChampsForPosition().add(Champion.Swain);
		$cs.getChampsForPosition().add(Champion.Leona);
		$cs.getChampsForPosition().add(Champion.Sona);
		$cs.getChampsForPosition().add(Champion.Yuumi);
		$cs.getChampsForPosition().add(Champion.Janna);
		$cs.getChampsForPosition().add(Champion.Zilean);
		$cs.getChampsForPosition().add(Champion.Bard);
		$cs.getChampsForPosition().add(Champion.Brand);
		$cs.getChampsForPosition().add(Champion.Xerath);
		$cs.getChampsForPosition().add(Champion.Zyra);
		$cs.getChampsForPosition().add(Champion.Taric);
		$cs.getChampsForPosition().add(Champion.Lulu);
		$cs.getChampsForPosition().add(Champion.Lux);
		$cs.getChampsForPosition().add(Champion.Soraka);
		$cs.getChampsForPosition().add(Champion.Karma);
		$cs.getChampsForPosition().add(Champion.VelKoz);
		$cs.getChampsForPosition().add(Champion.Rakan);
		$cs.getChampsForPosition().add(Champion.Alistar);
		$cs.getChampsForPosition().add(Champion.Braum);
end