package com.lolpicker.rules;

import com.lolpicker.model.ChampionPick;
import com.lolpicker.model.ChampionSelect;
import com.lolpicker.model.Champion;
import com.lolpicker.model.Clasz;
import com.lolpicker.model.StrongPoint;
import com.lolpicker.model.CompositionType;

rule "enemy team adheavy comp"
	salience -1
	when 
		$cs: ChampionSelect(enemyTeamComposition contains CompositionType.adheavy)
	then
		$cs.getCompositionCounters().add(Champion.Rammus);
		$cs.getCompositionCounters().add(Champion.Malphite);
		$cs.getCompositionCounters().add(Champion.Ornn);
		$cs.getCompositionCounters().add(Champion.Poppy);
		$cs.getCompositionCounters().add(Champion.Sejuani);
		$cs.getCompositionCounters().add(Champion.DrMundo);
		$cs.getCompositionCounters().add(Champion.Teemo);
		$cs.getCompositionCounters().add(Champion.Graves);
		$cs.getCompositionCounters().add(Champion.Quinn);
		$cs.getCompositionCounters().add(Champion.Alistar);
		$cs.getCompositionCounters().add(Champion.Braum);
		$cs.getCompositionCounters().add(Champion.Leona);
		$cs.getCompositionCounters().add(Champion.Taric);
		$cs.getCompositionCounters().add(Champion.Zilean);
		$cs.getCompositionCounters().add(Champion.Evelynn);
		$cs.getCompositionCounters().add(Champion.Trundle);
		$cs.getCompositionCounters().add(Champion.Fiddlesticks);
		$cs.getCompositionCounters().add(Champion.Gangplank);
		$cs.getCompositionCounters().add(Champion.Vladimir);
		$cs.getCompositionCounters().add(Champion.Anivia);
end

rule "enemy team apheavy comp"
	salience -1
	when 
		$cs: ChampionSelect(enemyTeamComposition contains CompositionType.apheavy)
	then
		$cs.getCompositionCounters().add(Champion.Galio);
		$cs.getCompositionCounters().add(Champion.ChoGath);
		$cs.getCompositionCounters().add(Champion.DrMundo);
		$cs.getCompositionCounters().add(Champion.Maokai);
		$cs.getCompositionCounters().add(Champion.Ornn);
		$cs.getCompositionCounters().add(Champion.Amumu);
		$cs.getCompositionCounters().add(Champion.Sejuani);
		$cs.getCompositionCounters().add(Champion.Sett);
		$cs.getCompositionCounters().add(Champion.Mordekaiser);
		$cs.getCompositionCounters().add(Champion.Morgana);
		$cs.getCompositionCounters().add(Champion.Alistar);
		$cs.getCompositionCounters().add(Champion.Braum);
		$cs.getCompositionCounters().add(Champion.Taric);
		$cs.getCompositionCounters().add(Champion.TahmKench);
		$cs.getCompositionCounters().add(Champion.Thresh);
		$cs.getCompositionCounters().add(Champion.Zilean);
		$cs.getCompositionCounters().add(Champion.Zac);
		$cs.getCompositionCounters().add(Champion.Trundle);
		$cs.getCompositionCounters().add(Champion.Olaf);
end

rule "enemy team tankheavy comp"
	salience -1
	when 
		$cs: ChampionSelect(enemyTeamComposition contains CompositionType.tankheavy)
	then
		$cs.getCompositionCounters().add(Champion.Vayne);
		$cs.getCompositionCounters().add(Champion.KogMaw);
		$cs.getCompositionCounters().add(Champion.Jinx);
		$cs.getCompositionCounters().add(Champion.Ashe);
		$cs.getCompositionCounters().add(Champion.Azir);
		$cs.getCompositionCounters().add(Champion.Cassiopeia);
		$cs.getCompositionCounters().add(Champion.Orianna);
		$cs.getCompositionCounters().add(Champion.Ryze);
		$cs.getCompositionCounters().add(Champion.Sylas);
		$cs.getCompositionCounters().add(Champion.ChoGath);
		$cs.getCompositionCounters().add(Champion.DrMundo);
		$cs.getCompositionCounters().add(Champion.Urgot);
		$cs.getCompositionCounters().add(Champion.Kled);
		$cs.getCompositionCounters().add(Champion.Gangplank);
		$cs.getCompositionCounters().add(Champion.Gnar);
end

rule "enemy team healer comp"
	salience -1
	when 
		$cs: ChampionSelect(enemyTeamComposition contains CompositionType.healerheavy)
	then
		$cs.getCompositionCounters().add(Champion.Kled);
		$cs.getCompositionCounters().add(Champion.Katarina);
		$cs.getCompositionCounters().add(Champion.Varus);
		$cs.getCompositionCounters().add(Champion.Syndra);
		$cs.getCompositionCounters().add(Champion.Orianna);
		$cs.getCompositionCounters().add(Champion.Kassadin);
		$cs.getCompositionCounters().add(Champion.Blitzcrank);
		$cs.getCompositionCounters().add(Champion.Brand);
		$cs.getCompositionCounters().add(Champion.Aphelios);
		$cs.getCompositionCounters().add(Champion.ChoGath);
		$cs.getCompositionCounters().add(Champion.Mordekaiser);
		$cs.getCompositionCounters().add(Champion.Evelynn);
		$cs.getCompositionCounters().add(Champion.Darius);
		$cs.getCompositionCounters().add(Champion.Garen);
		$cs.getCompositionCounters().add(Champion.Shaco);
end

rule "enemy team poke comp"
	salience -1
	when 
		$cs: ChampionSelect(enemyTeamComposition contains CompositionType.pokeheavy)
	then
		$cs.getCompositionCounters().add(Champion.Soraka);
		$cs.getCompositionCounters().add(Champion.Janna);
		$cs.getCompositionCounters().add(Champion.Lulu);
		$cs.getCompositionCounters().add(Champion.Nidalee);
		$cs.getCompositionCounters().add(Champion.Vladimir);
		$cs.getCompositionCounters().add(Champion.Alistar);
		$cs.getCompositionCounters().add(Champion.Ashe);
		$cs.getCompositionCounters().add(Champion.Azir);
		$cs.getCompositionCounters().add(Champion.Blitzcrank);
		$cs.getCompositionCounters().add(Champion.DrMundo);
		$cs.getCompositionCounters().add(Champion.Garen);
		$cs.getCompositionCounters().add(Champion.Gragas);
		$cs.getCompositionCounters().add(Champion.Leona);
		$cs.getCompositionCounters().add(Champion.LeeSin);
		$cs.getCompositionCounters().add(Champion.Nautilus);
		$cs.getCompositionCounters().add(Champion.Malphite);
		$cs.getCompositionCounters().add(Champion.Warwick);
end